language: elixir
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.10
      env:
        - CHECK_FORMAT=true
env:
  global:
    - MIX_HOME=$HOME/.mix
cache:
  directories:
    - $HOME/.mix
    - deps
    - _build
script:
  - mix compile --warnings-as-errors
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=prod mix compile --warnings-as-errors
  - mix docs
  - mix test
  - if [ "$CHECK_FORMAT" == "true" ]; then mix format --check-formatted; fi
  - travis_wait 30 mix dialyzer
